USE PROJECT;

SELECT * FROM RETAIL;

--1)IDENTIFY THE PRODUCTS WITH PRICE HIGHER THAN THE AVERAGE PRICE WITHIN THEIR CATEGORY------------------------------
------------------------------------USING CTE--------------------------------
WITH AVGCATPRI AS (
SELECT CATEGORY,PRODUCT_NAME,AVG(PRICE) AS 'AVERAGE_PRICE' FROM RETAIL
GROUP BY CATEGORY,PRODUCT_NAME
)
SELECT R.CATEGORY,APC.AVERAGE_PRICE,R.PRICE,R.PRODUCT_NAME FROM RETAIL R
INNER JOIN AVGCATPRI APC ON R.CATEGORY = APC.CATEGORY
WHERE R.PRICE > APC.AVERAGE_PRICE;
------------------------------------------------------------------------------------------------------------------------------------MODIFIED-----------------
WITH AVGCATPRI AS (
SELECT CATEGORY,PRODUCT_NAME,AVG(PRICE) AS 'AVERAGE_PRICE' FROM RETAIL
GROUP BY CATEGORY,PRODUCT_NAME
)
SELECT 
AVGCATPRI.CATEGORY,
AVGCATPRI.AVERAGE_PRICE,
AVGCATPRI.PRODUCT_NAME
FROM AVGCATPRI 
INNER JOIN RETAIL ON RETAIL.CATEGORY = AVGCATPRI.CATEGORY
WHERE RETAIL.PRICE > AVGCATPRI.AVERAGE_PRICE;

--2)FINDING CATEGORIES WITH HIGHEST AVERAGE RATING ACROSS ALL THE PRODUCTS----------------------------------------------

SELECT CATEGORY,PRODUCT_NAME,AVG(RATING) AS 'AVG_RATING' FROM RETAIL
GROUP BY CATEGORY,PRODUCT_NAME
ORDER BY AVG(RATING) DESC;

--3)FINDING MOST REVIEWED PRODUCT IN EACH WAREHOUSE----------------------------
WITH RANKED_PRODUCTS AS(
SELECT 
 PRODUCT_ID,
 REVIEWS,
 WAREHOUSE,
 ROW_NUMBER()OVER(PARTITION BY WAREHOUSE ORDER BY REVIEWS DESC) AS 'RANK' 
FROM RETAIL
)
SELECT 
 PRODUCT_ID,
 REVIEWS,
 WAREHOUSE
FROM RANKED_PRODUCTS
WHERE
 RANK = 1;

 --4)FINDING PRODUCTS THAT HAVE HIGHER THAN AVERAGE PRICES WITHIN THEIR CATEGORY ALONG WITH THIER DISCOUNT AND SUPPLIER-------------------------------------------------
 WITH AVGCATPRI AS (
SELECT CATEGORY,SUPPLIER,AVG(PRICE) AS 'AVERAGE_PRICE',AVG(DISCOUNT) AS 'AVG_DISCOUNT'FROM RETAIL
GROUP BY CATEGORY,SUPPLIER
)
SELECT R.CATEGORY,APC.AVG_DISCOUNT,R.SUPPLIER,APC.AVERAGE_PRICE,R.PRICE,R.PRODUCT_NAME FROM RETAIL R
INNER JOIN AVGCATPRI APC ON R.CATEGORY = APC.CATEGORY
WHERE R.PRICE > APC.AVERAGE_PRICE;


--5)QUERY TO FIND TOP 2 PRODUCTS WITH THE HIGHEST AVERAGE RATING IN EACH CATEGORY------------------------------------------------------------------

WITH AVG_RATING AS(
SELECT
 PRODUCT_ID,
 CATEGORY,
 AVG(RATING) AS 'AVG_RATING'
FROM RETAIL
GROUP BY
 PRODUCT_ID,
 CATEGORY
),
RANKED_PRODUCTS AS(
SELECT
 PRODUCT_ID,
 CATEGORY,
 AVG_RATING,
 ROW_NUMBER()OVER(PARTITION BY CATEGORY ORDER BY AVG_RATING DESC) AS 'RANK'
FROM AVG_RATING
)
SELECT
 PRODUCT_ID,
 CATEGORY,
 AVG_RATING
FROM RANKED_PRODUCTS
WHERE
 RANK <= 2;
 
 --6)ANALYSIS ACROSS ALL RETURN POLICY CATEGORIES(COUNT,AVGSTOCK,TOTALSTOCK,WEIGHTED AVG RATING)---------------------------------------------------------------------------------------------

 SELECT RETURN_POLICY,COUNT(DISTINCT PRODUCT_ID) AS 'PRODUCT COUNT',AVG(STOCK_QUANTITY) AS 'AVG STOCK',SUM(STOCK_QUANTITY) AS 'TOTAL STOCK',SUM(RATING * REVIEWS)/SUM(REVIEWS) AS 'WEIGHTED AVG RATING' FROM RETAIL
 GROUP BY RETURN_POLICY
 ORDER BY RETURN_POLICY;

 
